# Generated by Django 5.0.6 on 2024-06-18 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veedeo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(default='images/veedeo.svg', upload_to='thumbnails/'),
        ),
    ]
