# Generated by Django 5.0.6 on 2024-06-12 20:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporalusermodel',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 13, 20, 19, 44, 115012, tzinfo=datetime.timezone.utc)),
        ),
    ]
