# Generated by Django 5.0.6 on 2024-06-13 13:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_temporalusermodel_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporalusermodel',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 14, 13, 24, 38, 293458, tzinfo=datetime.timezone.utc)),
        ),
    ]
