# Generated by Django 5.0.6 on 2024-06-15 22:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_temporalusermodel_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='temporalusermodel',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 16, 22, 10, 58, 413173, tzinfo=datetime.timezone.utc)),
        ),
    ]
