# Generated by Django 5.0.6 on 2024-06-18 11:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporalusermodel',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 19, 11, 38, 31, 810153, tzinfo=datetime.timezone.utc)),
        ),
    ]
