# Generated by Django 5.0.6 on 2024-06-18 13:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_temporalusermodel_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporalusermodel',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 19, 13, 11, 23, 589232, tzinfo=datetime.timezone.utc)),
        ),
    ]
